#!/bin/bash

echo "API Loan Record MBP/SB (SMS Banking)"
read -p "Masukkan MSISDN (Contoh: Diawali dengan 62 bukan 0, 6281234567890): " msisdn
read -p "Masukkan Transaction ID & Provisioning ID (Contoh: LOANSB0000/LOANSB0001/LOANSB0002, dst): " trxid_provisioning
read -p "Masukkan Channel ID (Contoh: pb/f0/h1): " channel_id
read -p "Masukkan Value (Contoh: 100/200/300/1000/2000/5000): " value

current_date_time=$(date +"%Y-%m-%d %H:%M:%S")

authorization=$(printf '%s' "$channel_id${msisdn}${trxid_provisioning}" | sha256sum | cut -f1 -d' ' | base64 -w 0 | sed 's/o=/==/g')
curl -vks --location --request POST 'https://10.49.141.2:6301/loena/v1/record' --header 'Content-Type: application/json' --header "Authorization: $authorization" --data "{ 'msisdn':'$msisdn', 'transaction_id':'$trxid_provisioning', 'timestamps':'$current_date_time', 'channel_id':'$channel_id', 'offer_id':'00000001', 'provisioning_id':'$trxid_provisioning', 'campaign_id':'C0001', 'value': $value}"
