#!/bin/bash

echo "API Loan Record Reguler v2"
read -p "Masukkan MSISDN (Contoh: Diawali dengan 62 bukan 0, 6281234567890): " msisdn
read -p "Masukkan Transaction ID & Channel Transaction ID (Contoh: LOANREGULAR0000/LOANREGULAR0001/LOANREGULAR0002, dst): " trxid_channel_trxid
read -p "Masukkan Channel ID (Contoh: pb/f0/h1): " channel_id
read -p "Masukkan Value (Contoh: 100/200/300/1000/2000/5000): " value

current_date_time=$(date +"%Y-%m-%d %H:%M:%S")

authorization=$(printf '%s' "${msisdn}${trxid_channel_trxid}" | sha256sum | cut -f1 -d' ' | base64 -w 0 | sed 's/o=/==/g')

curl -vks --location --request POST 'https://10.49.141.2:6202/loena/v2/record' \
--header 'Content-Type: application/json' \
--header "Authorization: $authorization" \
--data "{
  \"msisdn\": \"$msisdn\",
  \"transaction_id\": \"$trxid_channel_trxid\",
  \"channel_id\": \"$channel_id\",
  \"offer_id\": \"00006840\",
  \"payment_id\": \"00006840pay\",
  \"campaign_id\": \"CAMPAIGN_TEST\",
  \"value\": $value,
  \"is_retry\": false,
  \"channel_transaction_id\": \"r93322122212430561038516\",
  \"timestamp\": \"$current_date_time\"
}"
