#!/bin/bash

# Variables
yesterday=$(date --date="1 day ago" +%Y%m%d)

# 1. LOAN RECORDS
# PROD 5
echo "COUNTING DAILY LOAN RECORD PROD5..."
total_loan_record_prod5=$(ssh -t apps@prod5 "wc -l /apps/loena2/logs/frontend/tomcat_loan_record/*/LOAN_RECORD_${yesterday}_*.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL LOAN RECORD PROD 5=$total_loan_record_prod5"

# PROD 6
echo "COUNTING DAILY LOAN RECORD PROD6..."
total_loan_record_prod6=$(ssh -t apps@prod6 "wc -l /apps/loena2/logs/frontend/tomcat_loan_record/*/LOAN_RECORD_${yesterday}_*.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL LOAN RECORD PROD 6=$total_loan_record_prod6"

# BIREFUSR 5 & 6
echo "COUNTING THE TOTAL LOAN RECORD..."
total_loan_record_prod5_6=$(ssh -t apps@prod6 "ssh birefusr@10.54.3.206 \"wc -l /landing/tsel/higt_trans/loena_loan_record/LOAN_RECORD_${yesterday}_*.log | tail -n 1 | awk '{print \$1}'\"" )
echo "TOTAL LOAN RECORD PROD 5 & 6=$total_loan_record_prod5_6"

# BIREFUSR SNAPSHOT
echo "CHECKING LOAN RECORD SNAPSHOT..."
if ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 test -e "/landing/tsel/higt_trans/loena_loan_record_daily_snapshot/LOAN_RECORD_SNAPSHOT_${yesterday}_PAPP7.ctl"; then
  total_loan_record_snapshot=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "cat /landing/tsel/higt_trans/loena_loan_record_daily_snapshot/LOAN_RECORD_SNAPSHOT_${yesterday}_PAPP7.ctl")
else
  total_loan_record_snapshot=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "zcat /landing/tsel/higt_trans/loena_loan_record_daily_snapshot/LOAN_RECORD_SNAPSHOT_${yesterday}_PAPP7.ctl.gz")
fi

printf '%s\n' "$total_loan_record_snapshot"

# 2. PAYMENT RECORDS
# PROD5
echo "COUNTING DAILY PAYMENT RECORD PROD5..."
total_payment_record_prod5=$(ssh -t apps@prod5 "wc -l /apps/loena2/reporting/PAYMENT_${yesterday}_*_PAPP5.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL PAYMENT RECORD PROD 5=$total_payment_record_prod5"

# PROD6
echo "COUNTING DAILY PAYMENT RECORD PROD6..."
total_payment_record_prod6=$(ssh -t apps@prod6 "wc -l /apps/loena2/reporting/PAYMENT_${yesterday}_*_PAPP6.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL PAYMENT RECORD PROD 6=$total_payment_record_prod6"

# BIREFUSR 5 & 6
echo "COUNTING THE TOTAL PAYMENT RECORD..."
total_payment_record_prod5_6=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "wc -l /landing/tsel/higt_trans/loena_payment/PAYMENT_${yesterday}_*.log | tail -n 1 | awk '{print \$1}'")
echo "TOTAL PAYMENT RECORD PROD 5 & 6=$total_payment_record_prod5_6"

# BIREFUSR SNAPSHOT
echo "CHECKING PAYMENT RECORD SNAPSHOT..."
if ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 test -e "/landing/tsel/higt_trans/loena_payment_record_daily_snapshot/PAYMENT_RECORD_SNAPSHOT_${yesterday}_PAPP7.ctl"; then
  total_payment_record_snapshot=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "cat /landing/tsel/higt_trans/loena_payment_record_daily_snapshot/PAYMENT_RECORD_SNAPSHOT_${yesterday}_PAPP7.ctl")
else
  total_payment_record_snapshot=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "zcat /landing/tsel/higt_trans/loena_payment_record_daily_snapshot/PAYMENT_RECORD_SNAPSHOT_${yesterday}_PAPP7.ctl.gz")
fi

printf '%s\n' "$total_payment_record_snapshot"

# 3. PAYMENT REMINDER RECORDS
# PROD13
echo "COUNTING DAILY PAYMENT RECORD PROD13..."
total_payment_reminder_prod13=$(ssh -t apps@prod13 "wc -l /apps/loena2/logs/backend/be_rp/*/PAYMENT_REMINDER_${yesterday}_*.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL PAYMENT RECORD PROD 13=$total_payment_reminder_prod13"

# PROD14
echo "COUNTING DAILY PAYMENT RECORD PROD14..."
total_payment_record_prod6=$(ssh -t apps@prod14 "wc -l /apps/loena2/logs/backend/be_rp/*/PAYMENT_REMINDER_${yesterday}_*.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL PAYMENT RECORD PROD 14=$total_payment_reminder_prod13"

# BIREFUSR 13 & 14
echo "COUNTING THE TOTAL PAYMENT REMINDER..."
total_payment_reminder_prod13_14=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "wc -l /landing/tsel/higt_trans/loena_payment_reminder/PAYMENT_REMINDER_${yesterday}_*.log | tail -n 1 | awk '{print \$1}'")
echo "TOTAL PAYMENT REMINDER PROD 13 & 14=$total_payment_reminder_prod13_14"

# 4. LEDGER RECORDS
# PROD9
echo "COUNTING DAILY LEDGER RECORD PROD13..."
total_ledger_prod9=$(ssh -t apps@prod9 "wc -l /apps/loena2/logs/backend/be_ledger/*/LEDGER_${yesterday}_*.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL LEDGER PROD 9=$total_ledger_prod9"

# PROD10
echo "COUNTING DAILY LEDGER RECORD PROD14..."
total_ledger_prod10=$(ssh -t apps@prod10 "wc -l /apps/loena2/logs/backend/be_ledger/*/LEDGER_${yesterday}_*.log" | tail -n 1 | awk '{print $1}')
echo "TOTAL LEDGER PROD 10=$total_ledger_prod10"

# BIREFUSR 9 & 10
echo "COUNTING THE TOTAL LEDGER..."
total_ledger_prod9_10=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "wc -l /landing/tsel/higt_trans/loena_ledger/LEDGER_${yesterday}_*.log | tail -n 1 | awk '{print \$1}'")
echo "TOTAL LEDGER PROD 9 & 10=$total_ledger_prod9_10"

# BIREFUSR SNAPSHOT
echo "CHECKING PAYMENT RECORD SNAPSHOT..."
if ssh -t apps@prod10 ssh -t birefusr@10.54.3.206 test -e "/landing/tsel/higt_trans/loena_ledger_daily_snapshot/LEDGER_SNAPSHOT_${yesterday}_PAPP9.ctl"; then
  total_ledger_snapshot=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "cat /landing/tsel/higt_trans/loena_ledger_daily_snapshot/LEDGER_SNAPSHOT_${yesterday}_PAPP9.ctl")
else
  total_ledger_snapshot=$(ssh -t apps@prod6 ssh -t birefusr@10.54.3.206 "zcat /landing/tsel/higt_trans/loena_ledger_daily_snapshot/LEDGER_SNAPSHOT_${yesterday}_PAPP9.ctl.gz")
fi

printf '%s\n' "$total_ledger_snapshot"
