#!/bin/bash

# Variables
yesterday=$(date --date="1 day ago" +%Y%m%d)

# 2. PAYMENT RECORD
# PROD 5
echo "COUNTING DAILY PAYMENT RECORD PROD5..."
total_payment_record_prod5=$(ssh -t apps@prod5 "wc -l /apps/loena2/reporting/PAYMENT_${yesterday}_*_PAPP5.log" | tail -n 1 | awk '{print "TOTAL PAYMENT RECORD PROD 5= " $1}')

# PROD 6
echo "COUNTING DAILY PAYMENT RECORD PROD6..."
total_payment_record_prod6=$(ssh -t apps@prod6 "wc -l /apps/loena2/reporting/PAYMENT_${yesterday}_*_PAPP6.log" | tail -n 1 | awk '{print "TOTAL PAYMENT RECORD PROD 6= " $1}')

# GABUNGAN PAYMENT RECORD 5 & 6 DAN PAYMENT SNAPSHOT
echo "COUNTING THE TOTAL PAYMENT RECORD..."
total_payment_record_prod5_6=$(ssh -t apps@prod6 ssh birefusr@10.54.3.206 "wc -l /landing/tsel/higt_trans/loena_payment/PAYMENT_${yesterday}_*.log" | tail -n 1 | awk '{print "TOTAL PAYMENT RECORD PROD 5 dan 6= " $1}')

# PAYMENT SNAPSHOT
echo "COUNTING THE TOTAL PAYMENT RECORD SNAPSHOT..."
total_payment_record_snapshot=$(ssh -t -v apps@prod6 ssh -t -v birefusr@10.54.3.206 "cat /landing/tsel/higt_trans/loena_loan_record_daily_snapshot/LOAN_RECORD_SNAPSHOT_${yesterday}_PAPP7.ctl 2> /dev/null | awk -F '|' '{print \"TOTAL PAYMENT RECORD SNAPSHOT= \" $2}'")

echo "$total_payment_record_prod5"
echo "$total_payment_record_prod6"
echo "$total_payment_record_prod5_6"
echo "$total_payment_record_snapshot"
